import React from 'react'
import Inversehoricard from '../../component/Inversehoricard';
import Overlapdiv from '../../component/Overlapdiv'
import Horicariimg from '../../component/Horicariimg'
import NavforHorizontalcard from '../../component/NavforHorizontalcard';

function Beyondacademices() {
    return (
        <>
            <Overlapdiv />
            <NavforHorizontalcard/>
            <Horicariimg title="Bagless Day" description="In keeping with the vision and mission statement of the school, it is one of our primary objectives to ensure holistic development and learning, in a joyful environment. A heavy bag has been a debatable topic for ages. The NEP 2020 recommends that all children must experience a minimum of ten bagless days in a year. This unique bagless day project was adopted for the students of Class 5." p1="On every academic Day 1, the students of a particular section of Class 5 have been exempted from bringing any books or notebooks to class. Instead of focusing on rote-learning, lessons are being designed in such a way that students get an opportunity to practically experience the things learnt in books and to acquire important life skills."img="baglessday1.png" />
            <Inversehoricard title="Excursion" description="Excursions are a must, especially for students. They have a great educational value. That is why schools often organize excursions for the students. Apart from educating students and exposing them to various experiences, it is a great means of recreation. It is the day all students wait for eagerly." img="excursion.png" p1="Provides another dimension to class based learning and helps reinforce what has been taught in the classroom." p2="Students are excitement and energised by the anticipation of leaving the classroom." p3="Children have the opportunity to learn about and see new things in a less structured enviroment with more learning styles available." />
            <Horicariimg title="Sports" description="Physical activities play an essential role in the holistic development of students. It not only keeps them fit but fosters to their physical, social and emotional health. Along with catering to their physical and mental fitness it teaches them group commitment, team work, individual discipline and helps them create an apt attitude towards life in general. We, at N. K. Bagrodia Global School , firmly believe in all round development of our students and thus we emphasize equally on both academics and co-curricular activities. We envisage a system which aims at a multifaceted flowering of the child's physical, emotional, mental and spiritual personality." p1="Well structured sports program and modified games guided by expert coaches at N. K. Bagrodia Global School helps children develop fundamental movement skills and develop gross motor skills exclusively for the pre-primary kids. To ensure regular participation of students in different sports, we have made games curriculum a part of our educational process." p2="Global Bagrodians have bagged numerous accolades in sports like Gymnastics, Skating , badminton, yoga, basket ball, Hand ball, foot ball, table tennis etc at zonals, state, national and international levels, of which the Bagrodian fraternity is proud of." img="football1.png" />
            <Inversehoricard title="Exibition" description="N. K. Bagrodia Global School gives a platform to the students for organized display of their creativity. The work of the children is exhibited & appreciated. A host of exhibitions showcasing the creativity of the children is organized at various occasions in the school premises especially on PTM" img="exibation.png" p1="Cultural Exhibitions" p2="Art Exhibitions" p3="Science Exhibitions    " />
            <Horicariimg title="Project" description="A project is a collaborative enterprise carefully planned to achieve certain defined aim. N. K.  Bagrodia Global School  provides a platform to its students to undertake various projects to enhance the social, academic & intellectual skills of the children. This arouses creativity & a spirit of inquiry in children & provide them with in a depth knowledge of the content/ subject. Multifarious projects have been undertaken by children to explore new horizons:" img="project.png" />
            <Inversehoricard title="Workshop & Seminars" description="
            Along with being a great place to learn about educational research and strategies, workshops are a great place to meet other teachers with similar interests and make essential contacts that make teaching and learning easier. Workshops are also a great place to meet other educators who can help with situations more specific to teaching. They are a great opportunity to trade information. N.K.Bagrodia Global School took opportunities to be a part of various educative and informative workshops for students and teachers as well. " img="workshopandseminar.png" p1="Life Skills-Teachers W/S, Peer Pressure" p2="Gender Sensitivity" p3="Financial management in School" />
        </>
    )
}

export default Beyondacademices